/* XPM */
static char * Eraser[] = {
/* width height ncolors cpp [x_hot y_hot] */
"28 28 8 1 0 0",
/* colors */
" 	s iconColor12	m white	c yellow",
".	s iconColor2	m white	c white",
"X	s background	m black	c #949494949494",
"o	s iconGray5	m black	c #737373737373",
"O	s iconGray1	m white	c #dededededede",
"+	s iconGray3	m white	c #adadadadadad",
"@	s iconColor4	m white	c red",
"#	s iconColor1	m black	c black",
/* pixels */
" . XXXXXXXXXXXXXXXXXXXXXXXXX",
". . XXXXXXXXXXXXXXXXXXXXXXXX",
" . . XXXXXXXXXXXXXXXXXXXXXXX",
"o . . XXXXXXXXXXXXXXXXXXXXXX",
" o . . XXXXXXXXXXXXXXXXXXXXX",
"o o . . XXXXXXXXXXXXXXXXXXXX",
" o o . . XXXXXXXXXXXXXXXXXXX",
"o o o . . XXXXXXXXXXXXXXXXXX",
"Xo o o . . XXXXXXXXXXXXXXXXX",
"XXo o o . . XXXXXXXXXXXXXXXX",
"XXXo o o . . XXXXXXXXXXXXXXX",
"XXXXo o o . . XXXXXXXXXXXXXX",
"XXXXXo o o ...OXXXXXXXXXXXXX",
"XXXXXXo o o+...OXXXXXXXXXXXX",
"XXXXXXXo oo++...OXXXXXXXXXXX",
"XXXXXXXXo+oo++...OXXXXXXXXXX",
"XXXXXXXXX++oo++..ooXXXXXXXXX",
"XXXXXXXXXX++oo++o@.@XXXXXXXX",
"XXXXXXXXXXX++ooo@.@O@XXXXXXX",
"XXXXXXXXXXXX+oo@+@O@O@XXXXXX",
"XXXXXXXXXXXXXo@o@o@O@O@XXXXX",
"XXXXXXXXXXXXXXo@o@o@O@O@##X#",
"XXXXXXXXXXXXXXXo@o@o@O@##X#X",
"XXXXXXXXXXXXXXXXo@o@o@##X#X#",
"XXXXXXXXXXXXXXXXXo@o@##X#X#X",
"XXXXXXXXXXXXXXXXXXo@##X#X#X#",
"XXXXXXXXXXXXXXXXXXX##X#X#X#X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
