/* XPM */
static char * FillSolidsOn[] = {
/* width height ncolors cpp [x_hot y_hot] */
"28 28 7 1 0 0",
/* colors */
" 	s background	m black	c #949494949494",
".	s Color1	m black	c black",
"X	s Color11	m black	c darkkhaki",
"o	s Color12	m white	c yellow",
"O	s Color2	m white	c white",
"+	s Color10	m white	c cyan",
"@	s Color9	m black	c darkcyan",
/* pixels */
"                            ",
"                            ",
" .................          ",
" .XoXoXoXoXoXoXoX.O         ",
" .oXoXoXoXoXoXoXo.O         ",
" .XoXoXoXoXoXoXoX.O         ",
" .oXoXoXoXoXoXoXo.O         ",
" .XoXoXoXoXoXoXoX.O         ",
" .oXoXoXoXoXoXoXo.O         ",
" .XoXoXoXoXoXoXo.....       ",
" .oXoXoXoXoXoX..+@+@+..     ",
" .XoXoXoXoXoX.@+@+@+@+@.    ",
" .oXoXoXoXoX.@+@+@+@+@+@.   ",
" .XoXoXoXoX.@+@+@+@+@+@+@.  ",
" .oXoXoXoXo.+@+@+@+@+@+@+.  ",
" ..........+@+@+@+@+@+@+@+. ",
"  OOOOOOOO.@+@+@+@+@+@+@+@.O",
"          .+@+@+@+@+@+@+@+.O",
"          .@+@+@+@+@+@+@+@.O",
"          .+@+@+@+@+@+@+@+.O",
"           .+@+@+@+@+@+@+.O ",
"           .@+@+@+@+@+@+@.O ",
"            .@+@+@+@+@+@.O  ",
"             .@+@+@+@+@.O   ",
"              ..+@+@+..O    ",
"                .....OO     ",
"                 OOOO       ",
"                            "};
