/* XPM */
static char * Line[] = {
/* width height ncolors cpp [x_hot y_hot] */
"28 28 2 1 0 0",
/* colors */
" 	s background	m black	c #949494949494",
".	s iconColor1	m black	c black",
/* pixels */
"                            ",
"                            ",
"                            ",
"      .                     ",
"       .                    ",
"       .                    ",
"        .                   ",
"        .                   ",
"         .                  ",
"          .                 ",
"          .                 ",
"           .                ",
"            .               ",
"            .               ",
"             .              ",
"             .              ",
"              .             ",
"               .            ",
"               .            ",
"                .           ",
"                 .          ",
"                 .          ",
"                  .         ",
"                  .         ",
"                   .        ",
"                            ",
"                            ",
"                            "};
