/* XPM */
static char * PaintBucket[] = {
/* width height ncolors cpp [x_hot y_hot] */
"28 28 13 1 0 0",
/* colors */
" 	s background	m black	c #949494949494",
".	s iconGray1	m white	c #dededededede",
"X	s iconColor1	m black	c black",
"o	s iconColor2	m white	c white",
"O	s iconGray7	m black	c #424242424242",
"+	s iconGray8	m black	c #212121212121",
"@	s iconGray5	m black	c #737373737373",
"#	s iconColor6	m white	c green",
"$	s iconColor4	m white	c red",
"%	s iconColor12	m white	c yellow",
"&	s iconColor8	m white	c blue",
"*	s iconGray3	m white	c #adadadadadad",
"=	s iconGray4	m white	c #949494949494",
/* pixels */
"        .............       ",
"       ..XXXXXXXXXXXX.      ",
"      ..XX         .XX.     ",
"     ..XX           .XX     ",
"     .XX             .X     ",
"     .X              .X     ",
"     .X     .......  .X     ",
"     .X   oooOOOO... .X     ",
"     .X  o.OOOOOOO...XX     ",
"     .X o..OOOOOOOO...X     ",
"     .+o@...OOOOOOO..XX     ",
"     ..@@....OOOOOO...X     ",
"     ..@@@....OOOOO..@X     ",
"    ..@@@@@...O.O....@Xo    ",
"    ..####$$$%%%&&..**XXo   ",
"    ..##$$$$%%%%&...XoXoXo  ",
"    .##$$$$%%%%&&...XoXoXoo ",
"    .##$$$%%%%&&..@.X*ooXooo",
"    .#$$$%%%%&&..@.@XXXXXooo",
"    ##$$%%%%&&..O.@.@XXX..oo",
"    ##$$%o&&&..OOO.@.@.....o",
"    #$$%%%&...O.OOO.@.@.....",
"   ##$$%%&&.OOOO.OOO.@.@....",
"   ##$$%&&&.OOOOO.OOO.@.@...",
"   #$$%%&&&O.OOOOO.OOO.@.@..",
"   #$$%&&&..O.OOOOO.OOO.@.@.",
"  ##$%%&&&...O.OOOOO.OOO.@.@",
"  #$$%%&&&=...O.OOOOO.OOO.@."};
