/* XPM */
static char * Pencil[] = {
/* width height ncolors cpp [x_hot y_hot] */
"28 28 7 1 0 0",
/* colors */
" 	s background	m black	c #949494949494",
".	s iconColor12	m white	c yellow",
"X	s iconColor2	m white	c white",
"o	s iconGray5	m black	c #737373737373",
"O	s iconGray3	m white	c #adadadadadad",
"+	s iconGray1	m white	c #dededededede",
"@	s iconGray7	m black	c #424242424242",
/* pixels */
"                            ",
"                            ",
"                            ",
"                           .",
"                          .X",
"                         .X.",
"                        .X.X",
"                       .X.X.",
"                      .X.X.o",
"XXXXX                .X.X.o.",
"     XXX            .X.X.o.o",
"        X          .X.X.o.o.",
"         X        .X.X.o.o.o",
"          X      .X.X.o.o.o ",
"           X    .X.X.o.o.o  ",
"           X   .X.X.o.o.o   ",
"           X  O+XX.o.o.o    ",
"          X   OXX+o.o.o     ",
"        XX   OXX+ooo.o      ",
"     XXX     OX+ooo.o       ",
"    X       OX+ooooo        ",
"   X        O+ooooo         ",
"   X       O@ooooo          ",
"    X      @@@oo            ",
"     X     @@o              ",
"      XX  @@                ",
"        X@@                 ",
"                            "};
